### ISSUE TITLE
Clarify multi-homed client handling of multiple provider responses to mitigation requests

### ISSUE THREAD

**Issue by amortensen** [dotswg/dots-architecture#6]
Section 2.3 covers many-to-one and one-to-many DOTS agent relationships. One case raised in a multi-homed DOTS client scenario is how to handle a DOTS client simultaneously requesting mitigation from multiple distinct DOTS servers, each in a different domain. How should the client coordinate the responses in this scenario?

**Comment by amortensen** [comment]
I'm not sure this is a mode we want to support in the DOTS architecture. Mitigation providers insert themselves in the attack path through a few different means, most commonly through announcing routes or modifying DNS records. In either case, the mitigation provider has been delegated the authority to divert traffic for scrubbing. For example, if multiple, uncoordinated mitigation providers are all trying to divert traffic through BGP announcements, the service under attack may degrade further due to route flapping.

Maybe we need to define the order in which a multi-homed client signals different DOTS servers, or require that in the multi-homed deployment, the DOTS client assumes the DOTS servers are coordinating mitigation together.

**Comment by dcdolson** [comment]
I suggest not assuming coordination, but use the same request identifier (policy-id?) so that cooperating servers can recognize the request as a duplicate.

**Comment by amortensen** [comment]
Addressed by PR #10
